#!/usr/bin/env node

import { spawn, spawnSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { pickRandomPort } from "./lib/pick-dev-port.mjs";
import { ensureTauriIcons } from "./lib/ensure-tauri-icons.mjs";
import { spawnPnpm } from "./lib/spawn-pnpm.mjs";

const WORKSPACE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WEB_DIR = path.join(WORKSPACE_ROOT, "apps", "web");
const PORT_FILE = path.join(WORKSPACE_ROOT, ".dev", "desktop-web-port");
const TAURI_OVERLAY = path.join(WORKSPACE_ROOT, ".dev", "tauri-dev-overlay.json");
const DESKTOP_DIR = path.join(WORKSPACE_ROOT, "apps", "desktop");
const ENV_LOCAL = path.join(WEB_DIR, ".env.local");
const LOCK_FILE = path.join(WORKSPACE_ROOT, "apps", "web", ".next", "dev", "lock");
const PORT_MIN = 4900;
const PORT_MAX = 5899;

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: WORKSPACE_ROOT,
    stdio: "inherit",
    shell: false,
    ...options,
  });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function clearStaleDesktopProcesses() {
  const processNames =
    process.platform === "win32"
      ? ["vectis-desktop.exe", "vectis-node.exe"]
      : ["vectis-desktop", "vectis-node"];

  for (const name of processNames) {
    if (process.platform === "win32") {
      spawnSync("taskkill", ["/IM", name, "/F"], { stdio: "ignore", shell: false });
    } else {
      spawnSync("pkill", ["-x", name], { stdio: "ignore" });
    }
  }
}

async function clearStaleNextDevLock() {
  try {
    const raw = await fs.readFile(LOCK_FILE, "utf8");
    const lock = JSON.parse(raw);
    if (lock?.pid) {
      if (process.platform === "win32") {
        spawnSync("taskkill", ["/PID", String(lock.pid), "/F"], { stdio: "ignore", shell: false });
      } else {
        spawnSync("kill", [String(lock.pid)], { stdio: "ignore" });
      }
    }
  } catch {
    // no lock or unreadable
  }

  try {
    await fs.unlink(LOCK_FILE);
  } catch {
    // already gone
  }
}

async function writePortFiles(port) {
  await fs.mkdir(path.dirname(PORT_FILE), { recursive: true });
  await fs.writeFile(PORT_FILE, `${port}\n`, "utf8");
  await fs.writeFile(
    ENV_LOCAL,
    `# Auto-generated by scripts/dev-desktop.mjs — do not commit
PORT=${port}
NODE_API_BASE_URL=http://127.0.0.1:7878
NEXT_PUBLIC_NODE_API_BASE_URL=/api/node
`,
    "utf8"
  );
}

async function main() {
  clearStaleDesktopProcesses();
  await ensureTauriIcons();
  run(process.execPath, ["./scripts/stage-tauri-sidecar.mjs"]);

  await clearStaleNextDevLock();
  const port = await pickRandomPort(PORT_MIN, PORT_MAX);
  await writePortFiles(port);

  const devUrl = `http://127.0.0.1:${port}`;
  await fs.writeFile(
    TAURI_OVERLAY,
    `${JSON.stringify({ build: { devUrl } }, null, 2)}\n`,
    "utf8"
  );

  console.log(`Vectis desktop dev URL: ${devUrl}`);
  console.log(`Port file: .dev/desktop-web-port`);

  const overlayArg = path.relative(DESKTOP_DIR, TAURI_OVERLAY);
  const child = spawnPnpm(["exec", "tauri", "dev", "--config", overlayArg], {
    cwd: DESKTOP_DIR,
    stdio: "inherit",
  });

  child.on("exit", (code) => {
    process.exit(code ?? 1);
  });
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
